# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gabri\Google Drive\programas python\Exemplos e testes\projeto_integrador\oranges_identifier_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 790)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 900))
        MainWindow.setStyleSheet("background-color: rgb(253, 250, 239);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_22.addWidget(self.label_33)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(40, 48, 52);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min_h_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_h_slider.sizePolicy().hasHeightForWidth())
        self.min_h_slider.setSizePolicy(sizePolicy)
        self.min_h_slider.setMinimumSize(QtCore.QSize(130, 0))
        self.min_h_slider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.min_h_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: rgb(253, 246, 227);\n"
"    border: 2px solid #565a5e;\n"
"    width: 24px;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}")
        self.min_h_slider.setMaximum(255)
        self.min_h_slider.setSingleStep(1)
        self.min_h_slider.setPageStep(10)
        self.min_h_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_h_slider.setTickInterval(1)
        self.min_h_slider.setObjectName("min_h_slider")
        self.horizontalLayout.addWidget(self.min_h_slider)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.min_h_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_h_label.sizePolicy().hasHeightForWidth())
        self.min_h_label.setSizePolicy(sizePolicy)
        self.min_h_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.min_h_label.setFont(font)
        self.min_h_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.min_h_label.setObjectName("min_h_label")
        self.horizontalLayout.addWidget(self.min_h_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.max_h_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_h_slider.sizePolicy().hasHeightForWidth())
        self.max_h_slider.setSizePolicy(sizePolicy)
        self.max_h_slider.setMinimumSize(QtCore.QSize(130, 0))
        self.max_h_slider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.max_h_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: rgb(253, 246, 227);\n"
"    border: 2px solid #565a5e;\n"
"    width: 24px;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}")
        self.max_h_slider.setMaximum(255)
        self.max_h_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_h_slider.setTickInterval(1)
        self.max_h_slider.setObjectName("max_h_slider")
        self.horizontalLayout_2.addWidget(self.max_h_slider)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.max_h_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_h_label.sizePolicy().hasHeightForWidth())
        self.max_h_label.setSizePolicy(sizePolicy)
        self.max_h_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.max_h_label.setFont(font)
        self.max_h_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.max_h_label.setObjectName("max_h_label")
        self.horizontalLayout_2.addWidget(self.max_h_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.min_s_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_s_slider.sizePolicy().hasHeightForWidth())
        self.min_s_slider.setSizePolicy(sizePolicy)
        self.min_s_slider.setMinimumSize(QtCore.QSize(130, 0))
        self.min_s_slider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.min_s_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: rgb(253, 246, 227);\n"
"    border: 2px solid #565a5e;\n"
"    width: 24px;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}")
        self.min_s_slider.setMaximum(255)
        self.min_s_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_s_slider.setTickInterval(1)
        self.min_s_slider.setObjectName("min_s_slider")
        self.horizontalLayout_3.addWidget(self.min_s_slider)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.min_s_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_s_label.sizePolicy().hasHeightForWidth())
        self.min_s_label.setSizePolicy(sizePolicy)
        self.min_s_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.min_s_label.setFont(font)
        self.min_s_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.min_s_label.setObjectName("min_s_label")
        self.horizontalLayout_3.addWidget(self.min_s_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.max_s_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_s_slider.sizePolicy().hasHeightForWidth())
        self.max_s_slider.setSizePolicy(sizePolicy)
        self.max_s_slider.setMinimumSize(QtCore.QSize(130, 0))
        self.max_s_slider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.max_s_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: rgb(253, 246, 227);\n"
"    border: 2px solid #565a5e;\n"
"    width: 24px;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}")
        self.max_s_slider.setMaximum(255)
        self.max_s_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_s_slider.setTickInterval(1)
        self.max_s_slider.setObjectName("max_s_slider")
        self.horizontalLayout_6.addWidget(self.max_s_slider)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.max_s_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_s_label.sizePolicy().hasHeightForWidth())
        self.max_s_label.setSizePolicy(sizePolicy)
        self.max_s_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.max_s_label.setFont(font)
        self.max_s_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.max_s_label.setObjectName("max_s_label")
        self.horizontalLayout_6.addWidget(self.max_s_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.min_v_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_v_slider.sizePolicy().hasHeightForWidth())
        self.min_v_slider.setSizePolicy(sizePolicy)
        self.min_v_slider.setMinimumSize(QtCore.QSize(130, 0))
        self.min_v_slider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.min_v_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: rgb(253, 246, 227);\n"
"    border: 2px solid #565a5e;\n"
"    width: 24px;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}")
        self.min_v_slider.setMaximum(255)
        self.min_v_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_v_slider.setTickInterval(1)
        self.min_v_slider.setObjectName("min_v_slider")
        self.horizontalLayout_5.addWidget(self.min_v_slider)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.min_v_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_v_label.sizePolicy().hasHeightForWidth())
        self.min_v_label.setSizePolicy(sizePolicy)
        self.min_v_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.min_v_label.setFont(font)
        self.min_v_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.min_v_label.setObjectName("min_v_label")
        self.horizontalLayout_5.addWidget(self.min_v_label)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.max_v_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_v_slider.sizePolicy().hasHeightForWidth())
        self.max_v_slider.setSizePolicy(sizePolicy)
        self.max_v_slider.setMinimumSize(QtCore.QSize(130, 0))
        self.max_v_slider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.max_v_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: rgb(253, 246, 227);\n"
"    border: 2px solid #565a5e;\n"
"    width: 24px;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}")
        self.max_v_slider.setMaximum(255)
        self.max_v_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_v_slider.setTickInterval(1)
        self.max_v_slider.setObjectName("max_v_slider")
        self.horizontalLayout_4.addWidget(self.max_v_slider)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.max_v_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_v_label.sizePolicy().hasHeightForWidth())
        self.max_v_label.setSizePolicy(sizePolicy)
        self.max_v_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.max_v_label.setFont(font)
        self.max_v_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.max_v_label.setObjectName("max_v_label")
        self.horizontalLayout_4.addWidget(self.max_v_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_7.addWidget(self.line_3)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(300, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        spacerItem8 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.gaussian_kernel_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaussian_kernel_spin_box.sizePolicy().hasHeightForWidth())
        self.gaussian_kernel_spin_box.setSizePolicy(sizePolicy)
        self.gaussian_kernel_spin_box.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.gaussian_kernel_spin_box.setReadOnly(False)
        self.gaussian_kernel_spin_box.setMinimum(3)
        self.gaussian_kernel_spin_box.setMaximum(49)
        self.gaussian_kernel_spin_box.setSingleStep(2)
        self.gaussian_kernel_spin_box.setProperty("value", 5)
        self.gaussian_kernel_spin_box.setObjectName("gaussian_kernel_spin_box")
        self.horizontalLayout_11.addWidget(self.gaussian_kernel_spin_box)
        spacerItem10 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.opening_kernel_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opening_kernel_spin_box.sizePolicy().hasHeightForWidth())
        self.opening_kernel_spin_box.setSizePolicy(sizePolicy)
        self.opening_kernel_spin_box.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.opening_kernel_spin_box.setReadOnly(False)
        self.opening_kernel_spin_box.setMinimum(3)
        self.opening_kernel_spin_box.setMaximum(49)
        self.opening_kernel_spin_box.setSingleStep(2)
        self.opening_kernel_spin_box.setProperty("value", 5)
        self.opening_kernel_spin_box.setObjectName("opening_kernel_spin_box")
        self.horizontalLayout_10.addWidget(self.opening_kernel_spin_box)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        spacerItem13 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem13)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(300, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.min_frame_width_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.min_frame_width_spin_box.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.min_frame_width_spin_box.setMaximum(639)
        self.min_frame_width_spin_box.setProperty("value", 40)
        self.min_frame_width_spin_box.setObjectName("min_frame_width_spin_box")
        self.horizontalLayout_14.addWidget(self.min_frame_width_spin_box)
        spacerItem15 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.max_frame_width_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_frame_width_spin_box.sizePolicy().hasHeightForWidth())
        self.max_frame_width_spin_box.setSizePolicy(sizePolicy)
        self.max_frame_width_spin_box.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.max_frame_width_spin_box.setMaximum(639)
        self.max_frame_width_spin_box.setProperty("value", 600)
        self.max_frame_width_spin_box.setObjectName("max_frame_width_spin_box")
        self.horizontalLayout_14.addWidget(self.max_frame_width_spin_box)
        spacerItem16 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem17 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.min_frame_height_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.min_frame_height_spin_box.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.min_frame_height_spin_box.setMaximum(479)
        self.min_frame_height_spin_box.setProperty("value", 80)
        self.min_frame_height_spin_box.setObjectName("min_frame_height_spin_box")
        self.horizontalLayout_12.addWidget(self.min_frame_height_spin_box)
        spacerItem18 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 0))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.max_frame_height_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.max_frame_height_spin_box.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.max_frame_height_spin_box.setReadOnly(False)
        self.max_frame_height_spin_box.setMaximum(479)
        self.max_frame_height_spin_box.setProperty("value", 400)
        self.max_frame_height_spin_box.setObjectName("max_frame_height_spin_box")
        self.horizontalLayout_12.addWidget(self.max_frame_height_spin_box)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        spacerItem19 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem19)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 30))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_19.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_14.addWidget(self.label_19)
        spacerItem20 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem20)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.capture_line_position_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capture_line_position_slider.sizePolicy().hasHeightForWidth())
        self.capture_line_position_slider.setSizePolicy(sizePolicy)
        self.capture_line_position_slider.setMinimumSize(QtCore.QSize(150, 0))
        self.capture_line_position_slider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.capture_line_position_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: rgb(253, 246, 227);\n"
"    border: 2px solid #565a5e;\n"
"    width: 24px;\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}")
        self.capture_line_position_slider.setMinimum(150)
        self.capture_line_position_slider.setMaximum(500)
        self.capture_line_position_slider.setProperty("value", 300)
        self.capture_line_position_slider.setOrientation(QtCore.Qt.Horizontal)
        self.capture_line_position_slider.setObjectName("capture_line_position_slider")
        self.verticalLayout_14.addWidget(self.capture_line_position_slider)
        spacerItem21 = QtWidgets.QSpacerItem(5, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem21)
        spacerItem22 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem22)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_14.addWidget(self.label_22)
        spacerItem23 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem23)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_12.addWidget(self.label_21)
        self.capture_box_left_width_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capture_box_left_width_spin_box.sizePolicy().hasHeightForWidth())
        self.capture_box_left_width_spin_box.setSizePolicy(sizePolicy)
        self.capture_box_left_width_spin_box.setStyleSheet("color: rgb(40, 48, 52);")
        self.capture_box_left_width_spin_box.setMinimum(1)
        self.capture_box_left_width_spin_box.setMaximum(150)
        self.capture_box_left_width_spin_box.setSingleStep(1)
        self.capture_box_left_width_spin_box.setProperty("value", 150)
        self.capture_box_left_width_spin_box.setObjectName("capture_box_left_width_spin_box")
        self.verticalLayout_12.addWidget(self.capture_box_left_width_spin_box)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_13.addWidget(self.label_23)
        self.capture_box_right_width_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capture_box_right_width_spin_box.sizePolicy().hasHeightForWidth())
        self.capture_box_right_width_spin_box.setSizePolicy(sizePolicy)
        self.capture_box_right_width_spin_box.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.capture_box_right_width_spin_box.setMinimum(1)
        self.capture_box_right_width_spin_box.setMaximum(150)
        self.capture_box_right_width_spin_box.setSingleStep(1)
        self.capture_box_right_width_spin_box.setProperty("value", 150)
        self.capture_box_right_width_spin_box.setObjectName("capture_box_right_width_spin_box")
        self.verticalLayout_13.addWidget(self.capture_box_right_width_spin_box)
        self.horizontalLayout_16.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addLayout(self.verticalLayout_14)
        spacerItem24 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem24)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 30))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_11.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        spacerItem25 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem25)
        self.conveyor_state_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.conveyor_state_label.setFont(font)
        self.conveyor_state_label.setStyleSheet("border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;\n"
"color: rgb(255, 0, 0);")
        self.conveyor_state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.conveyor_state_label.setObjectName("conveyor_state_label")
        self.verticalLayout_9.addWidget(self.conveyor_state_label)
        spacerItem26 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem26)
        self.stop_conveyor_push_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_conveyor_push_button.sizePolicy().hasHeightForWidth())
        self.stop_conveyor_push_button.setSizePolicy(sizePolicy)
        self.stop_conveyor_push_button.setMaximumSize(QtCore.QSize(999999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop_conveyor_push_button.setFont(font)
        self.stop_conveyor_push_button.setStyleSheet("background-color: rgb(147, 103, 53);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(253, 246, 227);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.stop_conveyor_push_button.setObjectName("stop_conveyor_push_button")
        self.verticalLayout_9.addWidget(self.stop_conveyor_push_button)
        self.start_conveyor_push_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_conveyor_push_button.sizePolicy().hasHeightForWidth())
        self.start_conveyor_push_button.setSizePolicy(sizePolicy)
        self.start_conveyor_push_button.setMaximumSize(QtCore.QSize(99999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_conveyor_push_button.setFont(font)
        self.start_conveyor_push_button.setStyleSheet("background-color: rgb(147, 103, 53);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(253, 246, 227);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.start_conveyor_push_button.setObjectName("start_conveyor_push_button")
        self.verticalLayout_9.addWidget(self.start_conveyor_push_button)
        spacerItem27 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem27)
        self.horizontalLayout_17.addLayout(self.verticalLayout_9)
        spacerItem28 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem28)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(0, 30))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_31.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_31.setTextFormat(QtCore.Qt.AutoText)
        self.label_31.setScaledContents(False)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setWordWrap(False)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_20.addWidget(self.label_31)
        spacerItem29 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_20.addItem(spacerItem29)
        self.identifier_state_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.identifier_state_label.setFont(font)
        self.identifier_state_label.setStyleSheet("color: rgb(255, 0, 0);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.identifier_state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.identifier_state_label.setObjectName("identifier_state_label")
        self.verticalLayout_20.addWidget(self.identifier_state_label)
        spacerItem30 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_20.addItem(spacerItem30)
        self.stop_identifier_push_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_identifier_push_button.sizePolicy().hasHeightForWidth())
        self.stop_identifier_push_button.setSizePolicy(sizePolicy)
        self.stop_identifier_push_button.setMaximumSize(QtCore.QSize(999999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop_identifier_push_button.setFont(font)
        self.stop_identifier_push_button.setStyleSheet("background-color: rgb(147, 103, 53);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(253, 246, 227);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.stop_identifier_push_button.setObjectName("stop_identifier_push_button")
        self.verticalLayout_20.addWidget(self.stop_identifier_push_button)
        self.start_identifier_push_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_identifier_push_button.sizePolicy().hasHeightForWidth())
        self.start_identifier_push_button.setSizePolicy(sizePolicy)
        self.start_identifier_push_button.setMaximumSize(QtCore.QSize(99999, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_identifier_push_button.setFont(font)
        self.start_identifier_push_button.setStyleSheet("background-color: rgb(147, 103, 53);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(253, 246, 227);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.start_identifier_push_button.setObjectName("start_identifier_push_button")
        self.verticalLayout_20.addWidget(self.start_identifier_push_button)
        spacerItem31 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem31)
        self.horizontalLayout_17.addLayout(self.verticalLayout_20)
        self.verticalLayout_21.addLayout(self.horizontalLayout_17)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem32)
        spacerItem33 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_21.addItem(spacerItem33)
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_21.addWidget(self.label_32)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 30))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_17.addWidget(self.label_24)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.last_color_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_color_label.sizePolicy().hasHeightForWidth())
        self.last_color_label.setSizePolicy(sizePolicy)
        self.last_color_label.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.last_color_label.setFont(font)
        self.last_color_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.last_color_label.setObjectName("last_color_label")
        self.horizontalLayout_13.addWidget(self.last_color_label)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem34)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_18.addWidget(self.label_27)
        self.last_diameter_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_diameter_label.sizePolicy().hasHeightForWidth())
        self.last_diameter_label.setSizePolicy(sizePolicy)
        self.last_diameter_label.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.last_diameter_label.setFont(font)
        self.last_diameter_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.last_diameter_label.setObjectName("last_diameter_label")
        self.horizontalLayout_18.addWidget(self.last_diameter_label)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem35)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.horizontalLayout_21.addLayout(self.verticalLayout_17)
        self.last_color_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_color_frame.sizePolicy().hasHeightForWidth())
        self.last_color_frame.setSizePolicy(sizePolicy)
        self.last_color_frame.setMinimumSize(QtCore.QSize(50, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 250, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.last_color_frame.setPalette(palette)
        self.last_color_frame.setStyleSheet("border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.last_color_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.last_color_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.last_color_frame.setLineWidth(2)
        self.last_color_frame.setObjectName("last_color_frame")
        self.horizontalLayout_21.addWidget(self.last_color_frame)
        self.verticalLayout_19.addLayout(self.horizontalLayout_21)
        spacerItem36 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_19.addItem(spacerItem36)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 30))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: rgb(253, 246, 227);\n"
"color: rgb(40, 48, 52);\n"
"border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_18.addWidget(self.label_25)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_19.addWidget(self.label_28)
        self.average_color_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_color_label.sizePolicy().hasHeightForWidth())
        self.average_color_label.setSizePolicy(sizePolicy)
        self.average_color_label.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.average_color_label.setFont(font)
        self.average_color_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.average_color_label.setObjectName("average_color_label")
        self.horizontalLayout_19.addWidget(self.average_color_label)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem37)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_20.addWidget(self.label_29)
        self.average_diameter_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_diameter_label.sizePolicy().hasHeightForWidth())
        self.average_diameter_label.setSizePolicy(sizePolicy)
        self.average_diameter_label.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.average_diameter_label.setFont(font)
        self.average_diameter_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.average_diameter_label.setObjectName("average_diameter_label")
        self.horizontalLayout_20.addWidget(self.average_diameter_label)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem38)
        self.verticalLayout_16.addLayout(self.horizontalLayout_20)
        self.verticalLayout_18.addLayout(self.verticalLayout_16)
        self.horizontalLayout_22.addLayout(self.verticalLayout_18)
        self.average_color_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_color_frame.sizePolicy().hasHeightForWidth())
        self.average_color_frame.setSizePolicy(sizePolicy)
        self.average_color_frame.setMinimumSize(QtCore.QSize(50, 0))
        self.average_color_frame.setStyleSheet("border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.average_color_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.average_color_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.average_color_frame.setLineWidth(2)
        self.average_color_frame.setObjectName("average_color_frame")
        self.horizontalLayout_22.addWidget(self.average_color_frame)
        self.verticalLayout_19.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(40, 48, 52);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_23.addWidget(self.label_30)
        self.number_of_oranges_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_of_oranges_label.sizePolicy().hasHeightForWidth())
        self.number_of_oranges_label.setSizePolicy(sizePolicy)
        self.number_of_oranges_label.setMinimumSize(QtCore.QSize(60, 0))
        self.number_of_oranges_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.number_of_oranges_label.setFont(font)
        self.number_of_oranges_label.setStyleSheet("color: rgb(40, 48, 52);\n"
"")
        self.number_of_oranges_label.setObjectName("number_of_oranges_label")
        self.horizontalLayout_23.addWidget(self.number_of_oranges_label)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem39)
        self.verticalLayout_19.addLayout(self.horizontalLayout_23)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem40)
        self.horizontalLayout_24.addLayout(self.verticalLayout_19)
        self.main_graphics_view = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_graphics_view.sizePolicy().hasHeightForWidth())
        self.main_graphics_view.setSizePolicy(sizePolicy)
        self.main_graphics_view.setMinimumSize(QtCore.QSize(480, 360))
        self.main_graphics_view.setMaximumSize(QtCore.QSize(480, 360))
        self.main_graphics_view.setStyleSheet("border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.main_graphics_view.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_graphics_view.setObjectName("main_graphics_view")
        self.horizontalLayout_24.addWidget(self.main_graphics_view)
        self.segmentation_graphics_view = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segmentation_graphics_view.sizePolicy().hasHeightForWidth())
        self.segmentation_graphics_view.setSizePolicy(sizePolicy)
        self.segmentation_graphics_view.setMinimumSize(QtCore.QSize(360, 360))
        self.segmentation_graphics_view.setMaximumSize(QtCore.QSize(360, 360))
        self.segmentation_graphics_view.setStyleSheet("border-color: rgb(147, 103, 53);\n"
"border-width : 2px;\n"
"border-style:solid;")
        self.segmentation_graphics_view.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.segmentation_graphics_view.setObjectName("segmentation_graphics_view")
        self.horizontalLayout_24.addWidget(self.segmentation_graphics_view)
        self.verticalLayout_21.addLayout(self.horizontalLayout_24)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_33.setText(_translate("MainWindow", "Configuration"))
        self.label_9.setText(_translate("MainWindow", "Color Range"))
        self.label.setText(_translate("MainWindow", "Min Hue"))
        self.min_h_label.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Max Hue"))
        self.max_h_label.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Min Saturation"))
        self.min_s_label.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Max Saturation"))
        self.max_s_label.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Min Value"))
        self.min_v_label.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Max Value"))
        self.max_v_label.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Kernel Size"))
        self.label_7.setText(_translate("MainWindow", "Gaussian Kernel Size: "))
        self.label_8.setText(_translate("MainWindow", "Opening Kernel Size (Circular): "))
        self.label_12.setText(_translate("MainWindow", "Frame Dimension Range"))
        self.label_13.setText(_translate("MainWindow", "Width  "))
        self.label_14.setStyleSheet(_translate("MainWindow", "color: rgb(40, 48, 52);"))
        self.label_14.setText(_translate("MainWindow", "Min"))
        self.label_15.setStyleSheet(_translate("MainWindow", "color: rgb(40, 48, 52);"))
        self.label_15.setText(_translate("MainWindow", "Max"))
        self.label_17.setText(_translate("MainWindow", "   Height"))
        self.label_18.setStyleSheet(_translate("MainWindow", "color: rgb(40, 48, 52);"))
        self.label_18.setText(_translate("MainWindow", "Min"))
        self.label_16.setStyleSheet(_translate("MainWindow", "color: rgb(40, 48, 52);"))
        self.label_16.setText(_translate("MainWindow", "Max"))
        self.label_19.setText(_translate("MainWindow", "Capture Line"))
        self.label_20.setText(_translate("MainWindow", "Position"))
        self.label_22.setText(_translate("MainWindow", "Capture Box"))
        self.label_21.setText(_translate("MainWindow", "Left h"))
        self.label_23.setText(_translate("MainWindow", "Right h"))
        self.label_11.setText(_translate("MainWindow", "Conveyor"))
        self.conveyor_state_label.setText(_translate("MainWindow", "OFF"))
        self.stop_conveyor_push_button.setText(_translate("MainWindow", "Stop"))
        self.start_conveyor_push_button.setText(_translate("MainWindow", "Start"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Identifier</p><p align=\"center\"><br/></p></body></html>"))
        self.identifier_state_label.setText(_translate("MainWindow", "OFF"))
        self.stop_identifier_push_button.setText(_translate("MainWindow", "Stop"))
        self.start_identifier_push_button.setText(_translate("MainWindow", "Start"))
        self.label_32.setText(_translate("MainWindow", "Oranges Identifier"))
        self.label_24.setText(_translate("MainWindow", "Last Orange"))
        self.label_26.setText(_translate("MainWindow", "Color:"))
        self.last_color_label.setText(_translate("MainWindow", "-"))
        self.label_27.setText(_translate("MainWindow", "Diameter:"))
        self.last_diameter_label.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "Average Oranges"))
        self.label_28.setText(_translate("MainWindow", "Color:"))
        self.average_color_label.setText(_translate("MainWindow", "-"))
        self.label_29.setText(_translate("MainWindow", "Diameter:"))
        self.average_diameter_label.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "Number of oranges:"))
        self.number_of_oranges_label.setText(_translate("MainWindow", "0"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
